### ISSUE TITLE
No turtles when using exotic bounds

### ISSUE THREAD

**Issue by m0ose** [backspaces/asx#18] opened 2017-09-25 15:32 UTC
When using bounds outside of the normal ones the turtles don't get drawn. It could be a problem in the sprout function. 
I tested it with the Flocking model and the bounds ```const model = new FlockModel(document.body, {minX: -110, maxX: -105, minY: 40, maxY: 45}).start()```

**Comment by backspaces** [comment] 2017-09-25 15:56
Well, this is actually a two-fer: I initially thought this was due to the World object being without a patchSize. But that wasn't it, apparently I defaulted it correctly. I'll check. Probably sprout() tho.

Thank you, I need the usage.

**Comment by m0ose** [comment] 2017-09-25 16:07
![screen shot 2017-09-25 at 9 54 45 am](https://user-images.githubusercontent.com/393666/30818004-9ec622c0-a1d7-11e7-9cbb-c3fdfa3e5f5b.png)

This is using the bounds {minX: -10, maxX: 10, minY: 10, maxY: 30, patchSize:1}. 
So, I'm starting to think that view centers around the patches, but the patches are still centered at (0,0)

**Comment by backspaces** [comment] 2017-09-25 19:14
Boy, the image helps. And I can reproduce it.

I'm *think* the proper behavior should be:
- The world object should have a center that's the average of the x,y min/max values.
- The patches should be shifted using the center so to be under the turtles.
- The Three Orbit camera should point to the center.

In other words, we have both a bug and an architecture/design issue.

**Comment by backspaces** [comment] 2017-09-25 21:32
OK, my next commit will solve the patches location .. translating to the appropriate center of the World geometry, like this:
![snap 09 25 17-15 29 21](https://user-images.githubusercontent.com/124366/30831918-7ecbf75e-a206-11e7-96ed-62bcc44bad00.jpg)

It remains to decide on what would be the best default for the camera and the Orbit control. I have not changed that yet.

I'll keep this open for a bit while we decide.

**Comment by backspaces** [comment] 2017-09-25 21:57
Note: the new Model refactor requires using the latest models/* if you'd like to test the fix. We moved setup() out of the Model ctor.

**Comment by backspaces** [comment] 2017-09-25 23:44
After playing with this, using the Orbit control, I think we'll not mess with centering the patches in the view. Using the arrow keys, the camera can be moved to be centered in the view.

So I'll close this for now, it does fix the issue. We can open a new one for camera defaults.

**Comment by m0ose** [comment] 2017-09-26 17:23
I'm getting a strange result, using the new code. 
I put in ``` {minX:10, minY:30, maxX:10, maxY:30} ```
and got ...
![screen shot 2017-09-26 at 11 19 11 am](https://user-images.githubusercontent.com/393666/30874111-a75df392-a2ac-11e7-800c-958638dd7878.png)

One question I have is whether the camera should still be centered on the area even when the bounds are strange or not? I think, I would prefer to have it still centered on the area.

**Comment by backspaces** [comment] 2017-09-26 18:18
Confirmed. Sigh. A one-patch world should work. Reopening.

In terms of the camera centering, would you open an issue? Let's keep them separate and small.

**Comment by backspaces** [comment] 2017-10-01 19:49
I believe I've found how to center the patches under the turtles correctly. Here's the result I get using 
> const options = { minX: -110, maxX: -105, minY: 40, maxY: 45, patchSize: 1 }

![snap 10 01 17-13 17 08](https://user-images.githubusercontent.com/124366/31058100-30964d1a-a6ab-11e7-9b30-0234d07e8b9e.jpg)

.. where the axes grid is clearly pretty far away:
![snap 10 01 17-13 20 26](https://user-images.githubusercontent.com/124366/31058113-6dc92bc6-a6ab-11e7-973f-263d45ec1c39.jpg)

This solves the initial bug (turtles not over patches correctly) but exposes two other bugs!
* The spacing between turtles and patches varies according to the patch world size. Bigger the world, the closer the turtle layer is to the patch layer.
* The camera looks at the (optional) axes grid, not the center of the patches.

The spacing problem is due to the ThreeView separating the two layers by a small amount in order to eliminate problems with the z interference .. odd visual effects when they are on top of each other. This is currently a constant: the patches are at z = 1 and turtles = 2. That's fine for a wide world but if the world is small, the difference of 1 is too noticeable.

I'll submit these as separate Issues and commit the fix to this Issue.

**Closed by backspaces** 2017-10-01 19:49 UTC
